import axios from 'axios';
import React from 'react'
import Image from 'next/image'
import Footer from '@/Components/Footer';
// import ContactForm from '@/Components/contactForm'
import { useState } from "react";
import styles from '@/styles/contact.module.css'
import Head from 'next/head';
import Navbar from '@/Components/Navbar';

const contact = () => {
  const [input, setInput] = useState("");

  const handleSubmit = async (e) => {
        e.preventDefault();
       
  axios.post(`/api/set_task`, {task: input})
  .then((res)=> console.log(res))
  .catch((err)=> console.log(err));
  }
  return (<>
  <Head>
  <title>Cotact._.Me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
<link href="https://fonts.googleapis.com/css2?family=Dela+Gothic+One&display=swap" rel="stylesheet"></link>
<link rel="preconnect" href="https://fonts.googleapis.com"></link>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
<link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300&display=swap" rel="stylesheet"></link>
<link rel="preconnect" href="https://fonts.googleapis.com"></link>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
<link href="https://fonts.googleapis.com/css2?family=Figtree&display=swap" rel="stylesheet"></link>
<link href="https://fonts.googleapis.com/css2?family=Orelega+One&display=swap" rel="stylesheet"></link>
  </Head>
  <Navbar/>
  <div className={styles.container}>
  <div className={styles.line}>
    <div className={styles.name}>Talk to Samarth</div>
  </div>

  <div className={styles.mainc}>
    <h1 className={styles.headd}>Don't just stand there!</h1>
    <p className={styles.para}>Welcome to the thrilling contact section for Samarth Dhawan portfolio. Ready to take the plunge and chat with the creative genius behind these projects? Fear not, we have got you covered!</p>
  </div>
  <form onSubmit={handleSubmit}>
    <div className={styles.button}><h3 className={styles.h3}>Shoot a message!</h3></div>
   <textarea className={styles.vo} type="text" value={input} placeholder="Anything you want to ask!.." onChange={(e) => setInput(e.target.value)}/>
   <button className={styles.bu} type="submit">Submit</button>
   </form>

   <div className={styles.pics}>
    <div className={styles.fir}>
    <Image className={styles.myImg2} src="/cont1.jpg" width={300} height={320}/>
    </div>
    <div className={styles.sec}>
    <Image className={styles.myImg3} src="/cont2.jpg" width={320} height={320}/>
    </div>
    <div className={styles.thir}>
    <Image className={styles.myImg4} src="/cont3.jpg" width={320} height={320}/>
    </div>
   </div>
   <div className={styles.callfor}>
  <h3 className={styles.hre}>Get Connected!</h3>
  <p className={styles.paraa}>Arent you thirsty for innovative solutions and dynamic collaborations? Dont be shy, jump in and grasp the opportunity to connect with Samarth Dhawan. Skip the small talk, lets start creating an extraordinary project together!</p>
  </div>
  </div>
 
  </>)
}

export default contact


