import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Icon } from '@iconify/react';
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  function scrollWin() {
    window.scrollTo(0, 500);
  }


  return (
    <>
      <Head>
        <title>Samarth Dhawan: Coding Whiz!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
<link href="https://fonts.googleapis.com/css2?family=Oi&display=swap" rel="stylesheet"></link>
        
<link rel="preconnect" href="https://fonts.googleapis.com"></link>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
<link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@300&display=swap" rel="stylesheet"></link>  
<link rel="preconnect" href="https://fonts.googleapis.com"></link>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
<link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet"></link>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
<link href="https://fonts.googleapis.com/css2?family=Merriweather+Sans:wght@500&display=swap" rel="stylesheet"></link>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
<link href="https://fonts.googleapis.com/css2?family=Figtree&display=swap" rel="stylesheet"></link>

      </Head>
       <nav className={styles.mainnav}>
            <ul className={styles.hello}>
                 <Link className={styles.u} legacyBehavior href='/'><a className={styles.fer}><li>Home</li></a></Link>
                 <Link className={styles.u} legacyBehavior href='/'><a className={styles.fer}><li>About</li></a></Link> 
                <Link className={styles.u} legacyBehavior href='/Project'><a className={styles.fer}><li>Projects</li></a></Link>
                <Link className={styles.u} legacyBehavior href='/contact'><a className={styles.fer}><li>Contact</li></a></Link> 
            </ul>
        </nav> 
      
      
      <main className={styles.main}>




        <div className={styles.container}>
          <div className={styles.box}>
            <h3 className={styles.emo}>🚀</h3>
        <p className={styles.title}>Samarth Dhawan: Coding Whiz!</p>
        <div className={styles.buttons}>
       <Link href='/Project' className={styles.one}>My Projects</Link>
        <Link href='/contact' className={styles.two}>Get in Touch</Link>
        </div>
        </div>
        </div>

        <div className={styles.who}>
          <div className={styles.col1}>
            <p className={styles.sam}>Who is Samarth?</p>
            <p className={styles.para}>Samarth Dhawan, a final year Computer Science student oozing talent and skills that impress everyone. Excelling as a frontend web developer, Samarth has tackled Internships at prestigious organizations like Indian Institute of Technology, Patna, and an ever-growing React Developer at EngineerHub. Watch out, world!</p>
          </div>
          <div className={styles.col2}>
            <h1 className={styles.emog}>
          💻
          </h1>
          </div>
        </div>

        <div className={styles.tech}>
          <p className={styles.sam}>Tech Marvels</p>
          <div className={styles.inner}>
          <Image className={styles.myImg} src="/pic1.jpg" width={650} height={700}/>
          <div className={styles.left}>
          <Image className={styles.myImg2} src="/pic4.jpg" width={400} height={300}/>
          <Image className={styles.myImg3} src="/pic2.jpg" width={400} height={350}/>
          </div>
          </div>
        </div>


        <div className={styles.pail}>
          <div className={styles.onee}>
            <h1 className={styles.re}>🔬</h1>
            <p className={styles.ra}>1</p>
            <p className={styles.rd}>Research Intern</p>
          </div>
          <div className={styles.onee}>
          <h1 className={styles.re}>⭐</h1>
            <p className={styles.ra}>20+</p>
            <p className={styles.rd}>Web Projects</p>
          </div>
          <div className={styles.onee}>
          <h1 className={styles.re}>🤓</h1>
            <p className={styles.ra}>3</p>
            <p className={styles.rd}>Noteworthy Gigs</p>
          </div>
        </div>

        <div className={styles.stars}>
          <h1 className={styles.star}>🌟</h1>
          <h1 className={styles.star}>🌟</h1>
          <h1 className={styles.star}>🌟</h1>
          <h1 className={styles.star}>🌟</h1>
          <h1 className={styles.star}>🌟</h1>
        </div>

        <div className={styles.quer}>
          <p className={styles.sam}>Queries Galore</p>
          <div className={styles.first}>
            <div className={styles.w}>
              <p className={styles.f}>Frontend specialties?</p>
              <p className={styles.c}>Samarth specializes in HTML, CSS, JavaScript, and ReactJS.</p>
            </div>
            <div className={styles.p}>
            <p className={styles.f}>Tech Stack?</p>
              <p className={styles.c}>Full stack development using ReactJS, Redux, NodeJS, SQL/NoSQL databases.</p>
            </div>
          </div>
          <div className={styles.second}>
          <div className={styles.w}>
              <p className={styles.f}>Open to job opportunities?</p>
              <p className={styles.c}>Absolutely! Samarth is ready to take on challenging projects and showcase his expertise.</p>
            </div>
            <div className={styles.p}>
            <p className={styles.f}>Can I reach out?</p>
              <p className={styles.c}>Definitely! Hit the ‛Get in Touch’ button above!</p>
            </div>
          </div>
        </div>


        {/* <div className={styles.footer}>
          <div className={styles.con}>
           <div className={styles.col}>
            <p className={styles.coldf}>Projects</p>
            <p className={styles.cold}>Portfolio</p>
            <p className={styles.cold}>Research</p>
            <p className={styles.cold}>Open-source</p>
           </div>
           <div className={styles.col}>
           <p className={styles.coldf}>Skills</p>
            <p className={styles.cold}>Frontend</p>
            <p className={styles.cold}>Backend</p>
            <p className={styles.cold}>DevOps</p>
           </div>
           <div className={styles.col}>
           <p className={styles.coldf}>Connect</p>
            <p className={styles.cold}>LinkedIn</p>
            <p className={styles.cold}>Twitter</p>
            <p className={styles.cold}>GitHub</p>
           </div>
          </div>

          <div className={styles.below}>
            <div className={styles.f}>
            <p className={styles.content}>© 2023 Samarth Dhawan's Talent Showcase</p>
            </div>
            <div>
            <p className={styles.content}>
            <Icon icon="mdi:linkedin" />
            <Icon icon="mdi:twitter" />
            </p>
            </div>
          </div>
        </div> */}



<footer className={styles.footer}>
  <div className={styles.footer__addr}>
    <h1 className={styles.footer__logo}>Samarth Dhawan</h1>
        
    <h2>Contact</h2>
    
    <address>
     +91 9582860464<br/>
      <a className={styles.footer__btn} href="mailto:sd2140@srmist.edu.in">Email Me</a>
    </address>
  </div>
  
  <ul className={styles.footer__nav}>
    <li className={styles.nav__item}>
      <h2 className={styles.nav__title}>Projects</h2>

      <ul className={styles.nav__ul}>
        <li>
          <a href="#">Portfolio</a>
        </li>

        <li>
          <a href="#">Research</a>
        </li>
            
        <li>
          <a href="#">Open-Source</a>
        </li>
      </ul>
    </li>
    
    <li className={styles.nav__item}>
      <h2 className={styles.nav__title}>Skills</h2>
      
      <ul className={styles.nav__ul} >
        <li>
          <a href="#">Frontend</a>
        </li>
        
        <li>
          <a href="#">Backend</a>
        </li>
        
        <li>
          <a href="#">Designing</a>
        </li>
        
      </ul>
    </li>
    
    <li className={styles.nav__item}>
      <h2 className={styles.nav__title}>Connect</h2>
      
      <ul className={styles.nav__ul}>
        <li>
          <a href="https://www.linkedin.com/in/samarth-dhawan-a317821aa/">Linkedin</a>
        </li>
        
        <li>
          <a href="https://github.com/samarth2812">Github</a>
        </li>
        
        <li>
          <a href="#">Discord</a>
        </li>
      </ul>
    </li>
  </ul>
  
  <div className={styles.legal}>
    <p>&copy; 2023 Samarth Dhawan's Talent Showcase.</p>
    

  </div>
</footer>
      </main>



    </>
  )
}
